
import br.com.marcio.model.*;
import br.com.marcio.teste.GeraXMLEnvio;
import br.com.status.StatusServico;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marcio
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String teste = new StatusServico().verificaStatusServico("/home/marcio/miranda.p12", senha.getPassword());
        System.out.println(teste);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//         String caminhoCertificado = "/home/marcio/miranda.p12";
//        char[] senha = new char[6];
        
        
        NfeCabecalho nfeCabecalho = new NfeCabecalho();
        NfeEmitente emitente = new NfeEmitente();
        
        emitente.setCpfCnpj("12345678912345");
        emitente.setIe("123456789");
        emitente.setRazaoSocial("Marcio Andre Pereria Costa");
        emitente.setFantasia("TOTAL SERVICE INFORMATICA");
        emitente.setLogradouro("Av. Lazaro Moreira 907");
        emitente.setNumero("1234");
        emitente.setComplemento("Casa");
        emitente.setBairro("Jardim Planalto");
        emitente.setNomeMunicipio("Santa Vitoria");
        emitente.setUf("MG");
        emitente.setCep("38320-000");
        emitente.setCodigoPais(12);
        emitente.setNomePais("Brasil");
        emitente.setTelefone("32511651");
        

        nfeCabecalho.setCodigoNumerico("12345678");

        nfeCabecalho.setNaturezaOperacao("5102");
        nfeCabecalho.setIndicadorFormaPagamento("0");
        nfeCabecalho.setCodigoModelo("55");
        nfeCabecalho.setSerie("1");
        nfeCabecalho.setNumero("101");
        nfeCabecalho.setDataEntradaSaida(new Date());
        nfeCabecalho.setTipoEmissao("1");
        nfeCabecalho.setVersaoProcessoEmissao(3);
        //    nfeCabecalho.setCUF(emitente.getCodigoMunicipio());
        nfeCabecalho.setCodigoMunicipio(12);
        nfeCabecalho.setCodigoMunicipio(12);
        nfeCabecalho.setFinalidadeEmissao("123");
        nfeCabecalho.setTipoOperacao("2");
        nfeCabecalho.setDigitoChaveAcesso("1212");
        nfeCabecalho.setFormatoImpressaoDanfe("0");
        Ncm ncm = new Ncm();
        ncm.setId(1);
        ncm.setCodigo("99");

        //Detalhe
        NfeDetalhe nfeDetalhe = new NfeDetalhe();
        Produto produto = new Produto();
        produto.setDescricao("Exemplo geracao XML JAXB");
        produto.setId(1);
        produto.setNcm(ncm);
        produto.setValorVenda(BigDecimal.valueOf(12));
        List<NfeDetalhe> listaNfeDetalhe = new ArrayList<NfeDetalhe>();


        
        
        
        
//        for (int i = 0; i < 10; i++) {
         //   nfeDetalhe.setProduto(produto);
            listaNfeDetalhe.add(nfeDetalhe);
//        }


        /**
         * // * Dados do Produro //
         */
//        Prod prod = new Prod();  
//        prod.setCProd("2");  
//        prod.setXProd("Exemplo geracao XML JAXB");  
//        prod.setNCM("99");  
//        prod.setCFOP("5102");  
//        prod.setUCom("UND");  
//        prod.setQCom("2.0000");  
//        prod.setVUnCom("90.0000");  
//        prod.setVProd("180.00");  
//        prod.setUTrib("UND");  
//        prod.setQTrib("2.0000");  
//        prod.setVUnTrib("90.0000");  
//        prod.setIndTot("1");  
//        det.setProd(prod);  
        NfeDestinatario destinatario = new NfeDestinatario();
        destinatario.setRazaoSocial("");
        destinatario.setCpfCnpj("12345678912345");
        destinatario.setIe("123456789");
        destinatario.setLogradouro("Av. Sao Paulo, 145");
        destinatario.setComplemento("Casa");
        destinatario.setBairro("Centro");
        destinatario.setCodigoMunicipio(12);
        destinatario.setNomeMunicipio("Santa Vitoria");
        destinatario.setUf("MG");
        destinatario.setCep("38320-000");
        destinatario.setCodigoPais(12);
        destinatario.setNomePais("Brasil");
        destinatario.setTelefone("3432511651");

        GeraXMLEnvio gera = new GeraXMLEnvio();
        String teste = gera.gerarXMLEnvio(nfeCabecalho, emitente, destinatario, listaNfeDetalhe, "/home/marcio/miranda.p12", senha.getPassword());
        System.out.println(teste);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
